function searchTaxon() {
    var input = document.getElementById("searchInput").value.toLowerCase();
    var pages = {
        "prodiamesa": "prodiamesa_olivacea.html",
        "odontomesa": "odontomesa_fulva.html",
        "monodiamesa": "monodiamesa.html",
        "corynoneura": "corynoneura.html",
        "smittia": "smittia.html",
        "pseudosmittia": "pseudosmittia.html",
        "metriocnemus": "metriocnemus.html",
        "heterotanytarsus": "heterotanytarsus.html",
        "propsilocerus": "propsilocerus.html",
        "epoicocladius": "epoicocladius.html",
        "rheocricotopus": "rheocricotopus.html",
        "synorthocladius": "synorthocladius.html",
        "psectrocladius": "psectrocladius.html",
        "paracladius": "paracladius.html",
        "acricotopus": "acricotopus.html",
        "parorthocladius" : "parorthocladius.html",
        "chaetocladius" : "chaetocladius.html",
        "nanocladius" : "nanocladius.html",
        "parakiefferiella" : "parakiefferiella.html",
        "hydrobaenus" : "hydrobaenus.html",
        "bryophaenocladius": "bryophaenocladius.html",
        "parametriocnemus" : "parametriocnemus.html",
        "heterotrissocladius" : "heterotrissocladius.html",
        "brillia" : "brillia.html",
        "eukiefferiella" : "eukiefferiella.html",
        "thienemanniella" : "thienemanniella.html",
        "cricotopus" : "cricotopus_orthocladius_paratrichocladius.html",
        "orthocladius" : "cricotopus_orthocladius_paratrichocladius.html",
        "paratrichocladius" : "cricotopus_orthocladius_paratrichocladius.html",
        "euorthocladius" : "euorthocladius.html",
        "pseudorthocladius" : "pseudorthocladius.html",
        "paratrissocladius" : "paratrissocladius.html",
        "paralimnophyes" : "paralimnophyes.html",
        "limnophyes" : "limnophyes.html",
        "chironomus" : "chironomus.html",
        "cladopelma" : "cladopelma.html",
        "cryptochironomus" : "cryptochironomus.html",
        "cryptotendipes" : "cryptotendipes.html",
        "demicryptochironomus" : "demicryptochironomus.html",
        "dicrotendipes" : "dicrotendipes.html",
        "einfeldia" : "einfeldia.html",
        "endochironomus" : "endochironomus.html",
        "endochironomus tendens" : "endochironomus_tendens.html",
        "fleuria" : "fleuria_lacustris.html",
        "fleuria lacustris" : "fleuria_lacustris.html",
        "glyptotendipes" : "glyptotendipes.html",
        "harnischia" : "harnischia.html",
        "kiefferulus" : "kiefferulus_tendipediformis.html",
        "kiefferulus tendipediformis" : "kiefferulus_tendipediformis.html",
        "lauterborniella" : "lauterborniella.html",
        "microtendipes" : "microtendipes.html",
        "microtendipes rydalensis" : "microtendipes_rydalensis.html",
        "nilothauma" : "nilothauma_brayi.html",
        "nilothauma brayi" : "nilothauma_brayi.html",
        "pagastiella orophila" : "pagastiella_orophila.html",
        "pagastiella" : "pagastiella_orophila.html",
        "parachironomus" : "parachironomus.html",
        "paracladopelma" : "paracladopelma.html",
        "paralauterborniella nigrohalteris" : "paralauterborniella_nigrohalteris.html",
        "paratendipes" : "paratendipes.html",
        "phaenopsectra" : "phaenopsectra.html",
        "polypedilum" : "polypedilum.html",
        "sergentia" : "sergentia.html",
        "stenochironomus" : "stenochironomus.html",
        "tribelos" : "tribelos_intextus.html",
        "tribelos intextus" : "tribelos_intextus.html",
        "stictochironomus" : "stictochironomus.html",
        "xenochironomus" : "xenochironomus_xenolabis",
        "xenochironomus xenolabis" : "xenochironomus_xenolabis",
        "zavreliella marmorata" : "zavreliella_marmorata",
        "zavreliella" : "zavreliella_marmorata"



        // Ajoutez ici tous les taxons avec leur fichier HTML correspondant (attentention ici mettre le nom du taxon en minuscule)
    };

    if (pages[input]) {
        window.location.href = pages[input];
    } else {
        alert("Taxon inexistant ou mal orthographié, veuillez réessayer.");
    }
}
